Debug complete Now To Test

diff --git a/cluster/velero/jobs/sync-backblaze.yaml b/cluster/velero/jobs/sync-backblaze.yaml
--- a/cluster/velero/jobs/sync-backblaze.yaml
+++ b/cluster/velero/jobs/sync-backblaze.yaml
@@ -36,20 +36,17 @@ spec:
                   name: gitea-pat
                   key: token
             command:
-            - /bin/sh
-            - "-c"
-            - "apk update && apk add openssh && apk add bind-tools && dig git.dev.elcarpenter.com"
-            # - "/bin/sh"
-            # - "-ec"
-            # - |
-            #   set -o nounset
-            #   set -o errexit
-            #   if [ -z "${GITEA_TOKEN}" ]; then
-            #     printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
-            #     exit 1
-            #   fi
-            #   git clone --depth 1 "https://${GITEA_TOKEN}@git.dev.elcarpenter.com/dcplaya/RClone.git" /shared/rclone-conf
-            #   exit 0
+            - "/bin/sh"
+            - "-ec"
+            - |
+              set -o nounset
+              set -o errexit
+              if [ -z "${GITEA_TOKEN}" ]; then
+                printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
+                exit 1
+              fi
+              git clone --depth 1 "https://${GITEA_TOKEN}@git.dev.elcarpenter.com/dcplaya/RClone.git" /shared/rclone-conf
+              exit 0
             volumeMounts:
             - name: shared
               mountPath: /shared
